"""Add ships!

Revision ID: 35c7b5b2c9d6
Revises: fa7d1a1aa1d2
Create Date: 2021-11-04 23:45:57.558383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "35c7b5b2c9d6"
down_revision = "fa7d1a1aa1d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("sensors", sa.Integer(), nullable=True),
        sa.Column("firepower", sa.Integer(), nullable=True),
        sa.Column("durability", sa.Integer(), nullable=True),
        sa.Column("accomodation", sa.Integer(), nullable=True),
        sa.Column("speed", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "players_have_ships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("ship_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ship_id"],
            ["ships.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("players", "ship")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players", sa.Column("ship", mysql.VARCHAR(length=255), nullable=True)
    )
    op.drop_table("players_have_ships")
    op.drop_table("ships")
    # ### end Alembic commands ###
