"""Add players

Revision ID: 79b591985926
Revises: 
Create Date: 2021-11-04 22:17:06.165488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "79b591985926"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("players")
    # ### end Alembic commands ###
