"""Add ship

Revision ID: fa7d1a1aa1d2
Revises: 74ebf9298c35
Create Date: 2021-11-04 22:58:51.323053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa7d1a1aa1d2"
down_revision = "74ebf9298c35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("ship", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "ship")
    # ### end Alembic commands ###
