"""Add qualitiy category

Revision ID: 74ebf9298c35
Revises: 1e4e287b0125
Create Date: 2021-11-04 22:36:29.567258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ebf9298c35'
down_revision = '1e4e287b0125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualities', sa.Column('category', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualities', 'category')
    # ### end Alembic commands ###
