"""Add user current_location

Revision ID: 76cd8afe1a19
Revises: 5b1e3bfbec77
Create Date: 2023-07-13 13:20:49.600863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "76cd8afe1a19"
down_revision = "5b1e3bfbec77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("current_location_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_players_current_location_id_locations"),
            "locations",
            ["current_location_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_players_current_location_id_locations"), type_="foreignkey"
        )
        batch_op.drop_column("current_location_id")

    # ### end Alembic commands ###
